# 默认启用的插件
enable:
  - google
  - youdao
  - bing

# 彩色输出
colorful: true

plugins:
  youdao:
    # 重试次数
    retries: 2
    # 超时时间 单位毫秒
    timeout: 5000
    # 代理设置，支持 socks5，http，https
    #   关闭: false
    #   开启: socks://127.0.0.1:1080
    proxy: false

  google:
    retries: 2
    timeout: 5000
    proxy: false

  bing:
    retries: 2
    timeout: 5000
    proxy: false
